# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=500, null=True, verbose_name='Data')),
                ('created', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
